// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: testpb.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildingStatus int32

const (
	BuildingStatus_Broken    BuildingStatus = 0
	BuildingStatus_Normal    BuildingStatus = 1
	BuildingStatus_Building  BuildingStatus = 2
	BuildingStatus_Upgrading BuildingStatus = 3
	BuildingStatus_Removed   BuildingStatus = 4
)

// Enum value maps for BuildingStatus.
var (
	BuildingStatus_name = map[int32]string{
		0: "Broken",
		1: "Normal",
		2: "Building",
		3: "Upgrading",
		4: "Removed",
	}
	BuildingStatus_value = map[string]int32{
		"Broken":    0,
		"Normal":    1,
		"Building":  2,
		"Upgrading": 3,
		"Removed":   4,
	}
)

func (x BuildingStatus) Enum() *BuildingStatus {
	p := new(BuildingStatus)
	*p = x
	return p
}

func (x BuildingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_proto_enumTypes[0].Descriptor()
}

func (BuildingStatus) Type() protoreflect.EnumType {
	return &file_testpb_proto_enumTypes[0]
}

func (x BuildingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingStatus.Descriptor instead.
func (BuildingStatus) EnumDescriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{0}
}

type BuildingType int32

const (
	BuildingType_Unknown      BuildingType = 0
	BuildingType_HeadQuarters BuildingType = 1
	BuildingType_Academy      BuildingType = 2
	BuildingType_Wall         BuildingType = 3
	BuildingType_WatchTower   BuildingType = 4
	BuildingType_Hospital     BuildingType = 5
)

// Enum value maps for BuildingType.
var (
	BuildingType_name = map[int32]string{
		0: "Unknown",
		1: "HeadQuarters",
		2: "Academy",
		3: "Wall",
		4: "WatchTower",
		5: "Hospital",
	}
	BuildingType_value = map[string]int32{
		"Unknown":      0,
		"HeadQuarters": 1,
		"Academy":      2,
		"Wall":         3,
		"WatchTower":   4,
		"Hospital":     5,
	}
)

func (x BuildingType) Enum() *BuildingType {
	p := new(BuildingType)
	*p = x
	return p
}

func (x BuildingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingType) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_proto_enumTypes[1].Descriptor()
}

func (BuildingType) Type() protoreflect.EnumType {
	return &file_testpb_proto_enumTypes[1]
}

func (x BuildingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingType.Descriptor instead.
func (BuildingType) EnumDescriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{1}
}

type Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *Coord) Reset() {
	*x = Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{0}
}

func (x *Coord) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coord) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BuildingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32          `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type   BuildingType   `protobuf:"varint,2,opt,name=Type,proto3,enum=testdata.BuildingType" json:"Type,omitempty"`
	Status BuildingStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=testdata.BuildingStatus" json:"Status,omitempty"`
	Level  int32          `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	PosX   int32          `protobuf:"varint,5,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosY   int32          `protobuf:"varint,7,opt,name=PosY,proto3" json:"PosY,omitempty"`
}

func (x *BuildingInfo) Reset() {
	*x = BuildingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingInfo) ProtoMessage() {}

func (x *BuildingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingInfo.ProtoReflect.Descriptor instead.
func (*BuildingInfo) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{1}
}

func (x *BuildingInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildingInfo) GetType() BuildingType {
	if x != nil {
		return x.Type
	}
	return BuildingType_Unknown
}

func (x *BuildingInfo) GetStatus() BuildingStatus {
	if x != nil {
		return x.Status
	}
	return BuildingStatus_Broken
}

func (x *BuildingInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BuildingInfo) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *BuildingInfo) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

type BuildActionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuilderID int32  `protobuf:"varint,1,opt,name=BuilderID,proto3" json:"BuilderID,omitempty"`
	MoveTime  int64  `protobuf:"varint,2,opt,name=MoveTime,proto3" json:"MoveTime,omitempty"`
	FromPos   *Coord `protobuf:"bytes,3,opt,name=FromPos,proto3" json:"FromPos,omitempty"`
	TargetPos *Coord `protobuf:"bytes,4,opt,name=TargetPos,proto3" json:"TargetPos,omitempty"`
}

func (x *BuildActionInfo) Reset() {
	*x = BuildActionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildActionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildActionInfo) ProtoMessage() {}

func (x *BuildActionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildActionInfo.ProtoReflect.Descriptor instead.
func (*BuildActionInfo) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{2}
}

func (x *BuildActionInfo) GetBuilderID() int32 {
	if x != nil {
		return x.BuilderID
	}
	return 0
}

func (x *BuildActionInfo) GetMoveTime() int64 {
	if x != nil {
		return x.MoveTime
	}
	return 0
}

func (x *BuildActionInfo) GetFromPos() *Coord {
	if x != nil {
		return x.FromPos
	}
	return nil
}

func (x *BuildActionInfo) GetTargetPos() *Coord {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

type BuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   BuildingType     `protobuf:"varint,1,opt,name=Type,proto3,enum=testdata.BuildingType" json:"Type,omitempty"`
	PosX   int32            `protobuf:"varint,2,opt,name=PosX,proto3" json:"PosX,omitempty"`
	PosY   int32            `protobuf:"varint,3,opt,name=PosY,proto3" json:"PosY,omitempty"`
	CityID int32            `protobuf:"varint,5,opt,name=CityID,proto3" json:"CityID,omitempty"`
	ID     int32            `protobuf:"varint,6,opt,name=ID,proto3" json:"ID,omitempty"`
	Action *BuildActionInfo `protobuf:"bytes,8,opt,name=Action,proto3" json:"Action,omitempty"`
}

func (x *BuildReq) Reset() {
	*x = BuildReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildReq) ProtoMessage() {}

func (x *BuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildReq.ProtoReflect.Descriptor instead.
func (*BuildReq) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{3}
}

func (x *BuildReq) GetType() BuildingType {
	if x != nil {
		return x.Type
	}
	return BuildingType_Unknown
}

func (x *BuildReq) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *BuildReq) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *BuildReq) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

func (x *BuildReq) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BuildReq) GetAction() *BuildActionInfo {
	if x != nil {
		return x.Action
	}
	return nil
}

type BuildAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Info *BuildingInfo `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
}

func (x *BuildAck) Reset() {
	*x = BuildAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildAck) ProtoMessage() {}

func (x *BuildAck) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildAck.ProtoReflect.Descriptor instead.
func (*BuildAck) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{4}
}

func (x *BuildAck) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BuildAck) GetInfo() *BuildingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_testpb_proto protoreflect.FileDescriptor

var file_testpb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x23, 0x0a, 0x05, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12,
	0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x22, 0xba, 0x01,
	0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x4d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x4d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x46, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x46, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x09, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50,
	0x6f, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x2a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x6f, 0x73, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x58, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50,
	0x6f, 0x73, 0x59, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a,
	0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x52, 0x0a, 0x0e, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x10, 0x04, 0x2a, 0x62,
	0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x48,
	0x65, 0x61, 0x64, 0x51, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x73, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x61,
	0x6c, 0x6c, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x61, 0x74, 0x63, 0x68, 0x54, 0x6f, 0x77,
	0x65, 0x72, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c,
	0x10, 0x05, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testpb_proto_rawDescOnce sync.Once
	file_testpb_proto_rawDescData = file_testpb_proto_rawDesc
)

func file_testpb_proto_rawDescGZIP() []byte {
	file_testpb_proto_rawDescOnce.Do(func() {
		file_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_testpb_proto_rawDescData)
	})
	return file_testpb_proto_rawDescData
}

var file_testpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testpb_proto_goTypes = []interface{}{
	(BuildingStatus)(0),     // 0: testdata.BuildingStatus
	(BuildingType)(0),       // 1: testdata.BuildingType
	(*Coord)(nil),           // 2: testdata.Coord
	(*BuildingInfo)(nil),    // 3: testdata.BuildingInfo
	(*BuildActionInfo)(nil), // 4: testdata.BuildActionInfo
	(*BuildReq)(nil),        // 5: testdata.BuildReq
	(*BuildAck)(nil),        // 6: testdata.BuildAck
}
var file_testpb_proto_depIdxs = []int32{
	1, // 0: testdata.BuildingInfo.Type:type_name -> testdata.BuildingType
	0, // 1: testdata.BuildingInfo.Status:type_name -> testdata.BuildingStatus
	2, // 2: testdata.BuildActionInfo.FromPos:type_name -> testdata.Coord
	2, // 3: testdata.BuildActionInfo.TargetPos:type_name -> testdata.Coord
	1, // 4: testdata.BuildReq.Type:type_name -> testdata.BuildingType
	4, // 5: testdata.BuildReq.Action:type_name -> testdata.BuildActionInfo
	3, // 6: testdata.BuildAck.Info:type_name -> testdata.BuildingInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_testpb_proto_init() }
func file_testpb_proto_init() {
	if File_testpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildActionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testpb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_proto_goTypes,
		DependencyIndexes: file_testpb_proto_depIdxs,
		EnumInfos:         file_testpb_proto_enumTypes,
		MessageInfos:      file_testpb_proto_msgTypes,
	}.Build()
	File_testpb_proto = out.File
	file_testpb_proto_rawDesc = nil
	file_testpb_proto_goTypes = nil
	file_testpb_proto_depIdxs = nil
}
